# Generated by Django 5.2.2 on 2025-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов после 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_after2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов после 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_after3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов после 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов дo 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов дo 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов дo 3'),
        ),
    ]
